import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import {
  Sparkles, ChevronDown, ChevronUp, Clock, Flame, CheckCircle2, Loader2, ArrowRight,
} from "lucide-react";
import { api, mock, safe, type MealPlan } from "@/lib/api";
import { storage } from "@/lib/storage";
import { toast } from "sonner";

export const Route = createFileRoute("/meal-plans")({
  component: MealPlans,
});

const STEPS = [
  "Analyzing profile",
  "Finding recipes",
  "Optimizing nutrition",
  "Calculating calories",
  "Building grocery list",
  "Saving your plan",
];

function MealPlans() {
  const [plan, setPlan] = useState<MealPlan | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [openDay, setOpenDay] = useState<string | null>("Monday");

  useEffect(() => {
    const id = storage.getLastPlanId();
    if (id) safe(api.getPlan(id), mock.plan()).then((p) => { setPlan(p); setLoading(false); });
    else { setPlan(mock.plan()); setLoading(false); }
  }, []);

  async function generate() {
    setGenerating(true);
    setProgress(0);
    const userId = storage.getUserId() || "demo-user";
    // simulated progress
    const ticker = setInterval(() => {
      setProgress((p) => (p < 90 ? p + 5 : p));
    }, 350);
    try {
      let newPlan: MealPlan;
      try {
        newPlan = await api.generatePlan(userId);
      } catch {
        await new Promise((r) => setTimeout(r, 1500));
        newPlan = mock.plan();
        toast.message("Generated demo plan", { description: "Backend unreachable — showing a beautiful sample." });
      }
      setPlan(newPlan);
      storage.setLastPlanId(newPlan.id);
      setProgress(100);
      toast.success("Your meal plan is ready");
    } finally {
      clearInterval(ticker);
      setTimeout(() => setGenerating(false), 400);
    }
  }

  if (loading) return <SkeletonPage />;

  const s = plan?.week_summary ?? { healthy_score: 0, avg_calories: 0, avg_protein: 0, total_budget: 0 };

  return (
    <div className="space-y-8 animate-fade-up">
      <header className="flex items-end justify-between gap-4 flex-wrap">
        <div>
          <div className="text-[11px] uppercase tracking-wider text-text-light font-medium">Meal Plans</div>
          <h1 className="mt-1 text-3xl font-semibold tracking-tight">Your weekly plan</h1>
          <p className="mt-1 text-text-secondary text-sm">Generated by AI, balanced to your goal and budget.</p>
        </div>
        <button onClick={generate} disabled={generating} className="inline-flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-4 py-2.5 text-sm font-medium hover:opacity-90 transition disabled:opacity-60 shadow-soft">
          {generating ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
          {generating ? "Generating…" : "Generate new plan"}
        </button>
      </header>

      {generating && (
        <section className="rounded-2xl border border-border bg-surface shadow-soft p-6">
          <div className="flex items-center justify-between">
            <div className="text-sm font-semibold">Crafting your plan</div>
            <div className="text-xs text-text-light">~30 seconds</div>
          </div>
          <div className="mt-4 h-1.5 rounded-full bg-muted overflow-hidden">
            <div className="h-full hero-gradient transition-all duration-300" style={{ width: `${progress}%` }} />
          </div>
          <ul className="mt-5 grid sm:grid-cols-2 gap-2">
            {STEPS.map((label, i) => {
              const reached = progress >= ((i + 1) / STEPS.length) * 100;
              return (
                <li key={label} className="flex items-center gap-2 text-sm">
                  {reached ? <CheckCircle2 className="size-4 text-success" /> : <Loader2 className="size-4 animate-spin text-primary" />}
                  <span className={reached ? "text-text-primary" : "text-text-secondary"}>{label}</span>
                </li>
              );
            })}
          </ul>
        </section>
      )}

      {/* Summary */}
      <section className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <SummaryStat label="Healthy Score" value={`${s.healthy_score}`} unit="/100" tone="success" />
        <SummaryStat label="Avg Calories" value={s.avg_calories.toLocaleString()} unit="kcal" tone="primary" />
        <SummaryStat label="Avg Protein" value={`${s.avg_protein}g`} tone="accent" />
        <SummaryStat label="Weekly Budget" value={`$${s.total_budget}`} tone="warning" />
      </section>

      {/* Days */}
      <section className="space-y-3">
        {(plan?.days ?? []).map((d) => {
          const open = openDay === d.day;
          const proteinPct = Math.min(100, (d.protein / 180) * 100);
          const calPct = Math.min(100, (d.calories / 2500) * 100);
          return (
            <article key={d.day} className="rounded-2xl border border-border bg-surface shadow-soft overflow-hidden">
              <button onClick={() => setOpenDay(open ? null : d.day)} className="w-full p-5 flex items-center gap-4 text-left hover:bg-muted/30 transition">
                <div className="relative size-12 shrink-0">
                  <svg viewBox="0 0 36 36" className="size-12">
                    <circle cx="18" cy="18" r="15.5" fill="none" stroke="var(--border)" strokeWidth="3" />
                    <circle cx="18" cy="18" r="15.5" fill="none" stroke="var(--primary)" strokeWidth="3"
                      strokeDasharray={`${(calPct * 97) / 100} 97`} strokeLinecap="round" transform="rotate(-90 18 18)" />
                  </svg>
                  <div className="absolute inset-0 grid place-items-center text-[10px] font-semibold">{Math.round(calPct)}%</div>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="text-base font-semibold">{d.day}</h3>
                    <Badge status={d.status || "planned"} />
                  </div>
                  <div className="text-xs text-text-secondary mt-0.5">{d.calories} kcal · {d.protein}g protein · {d.meals.length} meals</div>
                  <div className="mt-2 h-1 rounded-full bg-muted overflow-hidden">
                    <div className="h-full bg-success" style={{ width: `${proteinPct}%` }} />
                  </div>
                </div>
                {open ? <ChevronUp className="size-4 text-text-light" /> : <ChevronDown className="size-4 text-text-light" />}
              </button>
              <div className={"grid transition-all duration-300 " + (open ? "grid-rows-[1fr]" : "grid-rows-[0fr]")}>
                <div className="overflow-hidden">
                  <div className="px-5 pb-5 grid sm:grid-cols-2 gap-3 border-t border-border pt-4">
                    {d.meals.map((m, idx) => (
                      <div key={idx} className="rounded-xl border border-border p-4 hover:shadow-elevated hover:-translate-y-0.5 transition">
                        <div className="flex items-center justify-between">
                          <span className="text-[11px] uppercase tracking-wider text-primary font-semibold">{m.type}</span>
                          <span className="text-[11px] text-text-light inline-flex items-center gap-1"><Clock className="size-3" />{m.prep_time ?? 10}m</span>
                        </div>
                        <div className="mt-2 text-sm font-medium leading-snug">{m.name}</div>
                        <div className="mt-3 flex items-center gap-3 text-xs text-text-secondary">
                          <span className="inline-flex items-center gap-1"><Flame className="size-3 text-warning" />{m.calories} kcal</span>
                          <span>·</span>
                          <span>{m.protein}g protein</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </article>
          );
        })}
      </section>

      <section className="rounded-2xl border border-border bg-primary-light/40 p-6 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h3 className="font-semibold">Ready to shop?</h3>
          <p className="text-sm text-text-secondary mt-0.5">Your grocery list is grouped and ready to print or export.</p>
        </div>
        <Link to="/grocery" className="inline-flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-4 py-2.5 text-sm font-medium hover:opacity-90 transition">
          Open grocery list <ArrowRight className="size-4" />
        </Link>
      </section>
    </div>
  );
}

function SummaryStat({ label, value, unit, tone }: { label: string; value: string; unit?: string; tone: "primary"|"accent"|"warning"|"success" }) {
  const tones: Record<string, string> = {
    primary: "from-indigo-500/10 to-violet-500/10",
    accent: "from-cyan-500/10 to-sky-500/10",
    warning: "from-amber-500/10 to-orange-500/10",
    success: "from-emerald-500/10 to-teal-500/10",
  };
  return (
    <div className={`rounded-xl border border-border bg-gradient-to-br ${tones[tone]} bg-surface p-4 shadow-soft`}>
      <div className="text-xs text-text-secondary font-medium">{label}</div>
      <div className="mt-1.5 text-2xl font-semibold tracking-tight">
        {value}{unit && <span className="text-sm font-normal text-text-light ml-1">{unit}</span>}
      </div>
    </div>
  );
}

function Badge({ status }: { status: string }) {
  const map: Record<string, string> = {
    completed: "bg-success/10 text-success",
    active: "bg-primary-light text-primary",
    planned: "bg-muted text-text-secondary",
    approved: "bg-success/10 text-success",
  };
  return <span className={`text-[10px] font-medium uppercase tracking-wider px-2 py-0.5 rounded-full ${map[status] || map.planned}`}>{status}</span>;
}

function SkeletonPage() {
  return (
    <div className="space-y-6">
      <div className="h-8 w-64 skeleton rounded-md" />
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-24 skeleton rounded-xl" />)}
      </div>
      {Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-20 skeleton rounded-2xl" />)}
    </div>
  );
}
