-- Smart Meal AI credit/admin setup
-- Run this once in Supabase SQL Editor.

alter table public.users
  add column if not exists email text,
  add column if not exists credits integer not null default 3,
  add column if not exists role text not null default 'user';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'users_credits_non_negative'
  ) then
    alter table public.users
      add constraint users_credits_non_negative check (credits >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'users_role_allowed'
  ) then
    alter table public.users
      add constraint users_role_allowed check (role in ('user', 'admin'));
  end if;
end $$;

-- Make the first/admin profile an admin.
-- Replace 18 with your backend admin user id if different.
update public.users
set role = 'admin'
where id = 18;

-- Optional: add or correct starting credits for existing users.
update public.users
set credits = 3
where credits is null;

-- Prevent duplicate signups once old duplicate/null-email rows are cleaned.
create unique index if not exists users_email_unique_non_blank
  on public.users (lower(email))
  where email is not null and btrim(email) <> '';

create table if not exists public.credit_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  requested_credits integer not null default 3 check (requested_credits > 0),
  granted_credits integer,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  note text default '',
  created_at timestamp with time zone not null default now(),
  resolved_at timestamp with time zone
);

create index if not exists credit_requests_status_idx
  on public.credit_requests(status);

create index if not exists credit_requests_user_id_idx
  on public.credit_requests(user_id);
